version: '3.8'

x-name:
 - &NAME 'piwigo'
 - &NET 'piwigo_net'

x-variables:
 - &DB_HOST 'db'
 - &DB_ROOT_PASSWORD 'GC8GfxsFaqFxq8nYhSKEVsZfB2pTmdEX'
 - &DB_DATABASE 'pwg'
 - &DB_USERNAME 'pwg12.1'
 - &DB_PASSWORD 'pwg12.1'
 - &DB_PREFIX '_piwigo'
 - &PWG_ADMIN_USERNAME 'admin'
 - &PWG_ADMIN_PASSWORD 'password'
 - &PWG_ADMIN_MAIL 'noreply@domain.tld'

x-template: &default-template
  environment:
    TZ: 'Europe/Amsterdam'
  networks:
    - net
  restart: "unless-stopped"


services:
  #MySQL Service
  db:
    <<: *default-template
    hostname: db
    container_name: db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: *DB_ROOT_PASSWORD
      MYSQL_DATABASE: *DB_DATABASE
      MYSQL_USER:  *DB_USERNAME
      MYSQL_PASSWORD:  *DB_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data


  #phpmyadmin
  piwigo_pma:
    <<: *default-template
    image: ghcr.io/linuxserver/phpmyadmin
    hostname: piwigo_pma
    container_name: piwigo_pma
    profiles:
      - debug
    environment:
      PMA_HOST: *DB_HOST
      PMA_USER: root
      PMA_PASSWORD: *DB_ROOT_PASSWORD
    ports:
      - "9501:80"

  # imagemagick:
    # <<: *default-template
    # image: dpokidov/imagemagick
    # hostname: imagemagick
    # container_name: imagemagick

#docker run -v /your/images:/imgs dpokidov/imagemagick /imgs/sample.png -resize 100x100 /imgs/resized-sample.png

  #PHP Service
  *NAME:
    <<: *default-template
    container_name: *NAME
    hostname: *NAME
    image: kipjr/php-piwigo:8.0
    build:
      context: src
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      PWG_DB_HOST: *DB_HOST
      PWG_DB_BASE: *DB_DATABASE
      PWG_DB_USER: *DB_USERNAME
      PWG_DB_PASSWORD: *DB_PASSWORD
      PWG_DB_PREFIX: *DB_PREFIX
      PWG_ADMIN_USERNAME: *PWG_ADMIN_USERNAME
      PWG_ADMIN_PASSWORD: *PWG_ADMIN_PASSWORD
      PWG_ADMIN_EMAIL: *PWG_ADMIN_MAIL
    volumes:
      - pwgdata:/app

volumes:
  dbdata:
    driver: local
  pwgdata:
    driver: local


#Docker Networks
networks:
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.8.200/29 #(8.201-8.206, 207)
    driver_opts:
      com.docker.network.bridge.name: *NET
