volumes:
  config:
    driver: local
  gallery:
    driver: local 
  dbdata:
    driver: local 

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PWG_NET:-192.168.8.128/26}


services:
  #MySQL Service
  piwigo.db:
    container_name: piwigo.db
    hostname: db
    image: "yobasystems/alpine-mariadb:latest"
    environment:
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-db}
      MYSQL_DATABASE: ${DB_DATABASE:-pwg}
      MYSQL_USER: ${DB_USERNAME:-pwg}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pwg}
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
    restart: "unless-stopped"
    networks:
      - net

  #PHP Service
  piwigo.php:
    container_name: piwigo.php
    hostname: php
    image: ghcr.io/kipjr/docker-piwigo:${VERSION_PIWIGO:-13.8.0}
    build:
     context: src
     args:
        - PWGVERSION=${VERSION_PIWIGO:-13.8.0}
    depends_on:
      - piwigo.db
    ports:
      - 7080:80
    restart: "unless-stopped"
    environment:
      TZ: "Europe/Amsterdam"
      PWG_DB_HOST: ${DB_HOST:-db}
      PWG_DB_BASE: ${DB_DATABASE:-pwg}
      PWG_DB_USER: ${DB_USERNAME:-pwg}
      PWG_DB_PASSWORD: ${DB_PASSWORD:-pwg}
      PWG_DB_PREFIX: ${DB_PREFIX:-pwg_}
      PWG_ADMIN_USERNAME: ${PWG_ADMIN_USERNAME:-admin}
      PWG_ADMIN_PASSWORD: ${PWG_ADMIN_PASSWORD:-password}
      PWG_ADMIN_EMAIL: ${PWG_ADMIN_EMAIL:-noreply@domain.tld}
    volumes:
      - ./config:/config
      - gallery:/gallery
    networks:
      - net

  #phpmyadmin
  piwigo.pma:
    container_name: piwigo.pma
    hostname: pma
    image: ghcr.io/linuxserver/phpmyadmin
    profiles:
      - debug
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD:-db}
    ports:
      - "${PWG_HOST_IP:-0.0.0.0}:${PWG_PORT:-7081}:80"
    restart: "unless-stopped"
    networks:
      - net

