volumes:
  data:
  scripts:
  db:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NET_SUBNET:-192.168.8.128/26}


services:
  piwigo.db:
    container_name: piwigo.db
    hostname: db
    image: mariadb:${VERSION_MARIADB:-lts}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-piwigodb}
      - MARIADB_USER=${MARIADB_USER:-piwigodb_user}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD} 
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      - db:/var/lib/mysql/
    restart: "always"
    networks:
      - net

  #PHP Service
  piwigo.php:
    container_name: piwigo.php
    hostname: php
    # image: piwigo/piwigo:${VERSION_PIWIGO:-latest}
    image: ghcr.io/kipjr/docker-piwigo:${VERSION_PIWIGO:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=REVERSE_PROXY"
      - "traefik.http.routers.${PROJECT}.rule=Host(`${PROJECT_FQDN}`)"
      - "traefik.http.routers.${PROJECT}.entrypoints=${PROJECT_ENTRYPOINT}"
      - "traefik.http.routers.${PROJECT}.tls.certresolver=${PROJECT_CERT_RESOLVER}"
      - "traefik.http.routers.${PROJECT}.tls.domains[0].main=${PROJECT_DOMAIN_MAIN}"
      - "traefik.http.routers.${PROJECT}.tls.domains[0].sans=${PROJECT_DOMAIN_SANS}"
      - "traefik.http.services.${PROJECT}.loadbalancer.server.port=80"
    build:
     context: ./src
     args:
       DEPLOY_ENV: "production"
       PHP_VERSION: "84"
       VERSION_PIWIGO: "${VERSION_PIWIGO:-16.4.0}"
    depends_on:
      - piwigo.db
    ports:
      - "${PWG_HOSTPORT:-7080}:80"
    restart: "unless-stopped"
    environment:
      - TZ=${TZ:-Europe/Amsterdm}
      - PIWIGO_UID=${PIWIGO_UID:-1000}
      - PIWIGO_GID=${PIWIGO_GID:-1000}
    volumes:
      - data:/var/www/html/piwigo/
      - scripts:/usr/local/bin/scripts/
    networks:
      - net

  #phpmyadmin
  piwigo.pma:
    container_name: piwigo.pma
    hostname: pma
    image: ghcr.io/linuxserver/phpmyadmin
    profiles:
      - debug
    environment:
      PMA_HOST: ${MARIADB_HOST:-db}
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD:-db}
    ports:
      - "${PMA_HOSTPORT:-7081}:80"
    restart: "unless-stopped"
    networks:
      - net
