volumes:
  config:
    driver: local
  gallery:
    driver: local
  initdb:
    driver: local
  db:
    driver: local 

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NET_SUBNET:-192.168.8.128/26}


services:
  #MySQL Service
  piwigo.db:
    container_name: piwigo.db
    hostname: db
    image: 'mariadb:10'
    environment:
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pwg}
      MYSQL_USER: ${MYSQL_USER:-pwg}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pwg}
    volumes:
      - db:/var/lib/mysql/
      - initdb:/docker-entrypoint-initdb.d
    restart: "always"
    networks:
      - net

  #PHP Service
  piwigo.php:
    container_name: piwigo.php
    hostname: php
    image: ghcr.io/kipjr/docker-piwigo:${VERSION_PIWIGO:-15.3.0}
    build:
     context: src
     args:
        - VERSION_PIWIGO=${VERSION_PIWIGO:-15.3.0}
    depends_on:
      - piwigo.db
    ports:
      - "${PWG_HOSTPORT:-7080}:80"
    restart: "unless-stopped"
    environment:
      TZ: "Europe/Amsterdam"
      PWG_DB_HOST: ${MYSQL_HOST:-db}
      PWG_DB_BASE: ${MYSQL_DATABASE:-pwg}
      PWG_DB_USER: ${MYSQL_USER:-pwg}
      PWG_DB_PASSWORD: ${MYSQL_PASSWORD:-pwg}
      PWG_DB_PREFIX: ${DB_PREFIX:-pwg_}
      PWG_ADMIN_USERNAME: ${PWG_ADMIN_USERNAME:-admin}
      PWG_ADMIN_PASSWORD: ${PWG_ADMIN_PASSWORD:-password}
      PWG_ADMIN_EMAIL: ${PWG_ADMIN_EMAIL:-noreply@domain.tld}
    volumes:
      - config:/config
      - gallery:/gallery
    networks:
      - net

  #phpmyadmin
  piwigo.pma:
    container_name: piwigo.pma
    hostname: pma
    image: ghcr.io/linuxserver/phpmyadmin
    profiles:
      - debug
    environment:
      PMA_HOST: ${MYSQL_HOST:-db}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-db}
    ports:
      - "${PMA_HOSTPORT:-7081}:80"
    restart: "unless-stopped"
    networks:
      - net
